stripe:
  private_key: ${STRIPE_PRIVATE_KEY}
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri:  ${AUTH0_DOMAIN}
  data:
    rest:
      base-path: /api
    mongodb:
      uri: mongodb://localhost:27888/htdb  #${MONGODB_URI}

auth0:
  connection: "Username-Password-Authentication"
  audience: "https://happy-tenant.meraklis.io/api"
  client_id: ${AUTH0_CLIENT_ID}
  client_secret: ${AUTH0_CLIENT_ID}
email:
  no-reply: "no-reply@meraklis.io"
  sendgrid-api-key: ${SENDGRID_API_KEY}
tenant-portal-login-url: "http://localhost:3000/tenant-portal/login"
