stripe:
  private-key: ${STRIPE_PRIVATE_KEY}
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri:  ${AUTH0_DOMAIN}
  data:
    mongodb:
      uri: mongodb://localhost:27888/htdb
    rest:
      base-path: /api
auth0:
  connection: "Username-Password-Authentication"
  audience: "https://happy-tenant.meraklis.io/api"
  client_id: ${AUTH0_CLIENT_ID}
  client_secret: ${AUTH0_CLIENT_ID}
email:
  no-reply: "no-reply@meraklis.io"
  sendgrid-api-key: ${SENDGRID_API_KEY}
landlord-portal-url: "http://localhost:3000"
tenant-portal-url: "http://localhost:3000/tenant-portal"
---

spring:
  profiles: test
  data:
    mongodb:
      uri: mongodb://localhost:27888/htdb
---
spring:
  profiles: dev
  data:
    mongodb:
      uri: ${MONGODB_URI}
landlord-portal-url: "https://happy-tenant.herokuapp.com"
tenant-portal-url: "https://happy-tenant.herokuapp.com/tenant-portal"
